apiVersion: v1
kind: Service
metadata:
  # Do not use fullname,
  # so that the service could be accessed by using kube-dns
  name: {{ template "basic-service.name" . }}
  labels:
    app: {{ template "basic-service.name" . }}
    chart: {{ template "basic-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- $ports := required "Values.ports is required and must be a list" .Values.ports -}}
{{- range $index, $port := $ports }}
    - name: {{ required (printf "each Values.ports[%d].name is required" $index) $port.name }}
      port: {{ required (printf "each Values.ports[%d].port is required" $index) $port.port }}
      targetPort: {{ default $port.port $port.targetPort }}
      protocol: {{ default "TCP" $port.protocol }}
{{- end -}}
  selector:
    app: {{ template "basic-service.name" . }}
    release: {{ .Release.Name }}
